language: "php"

php:
  - "5.3"
  - "5.3.3"
  - "5.4"
  - "5.5"

matrix:
  allow_failures:
    - php: "5.5"

before_script:
  - "composer install --prefer-source"
  - "pear install pear/PHP_CodeSniffer && phpenv rehash"

script:
    - "phpunit -c test"
    - "phpcs --encoding=utf-8 --extensions=php --standard=test/phpcs.xml -nsp ./"

after_script:
  - "wget --quiet http://mauris.sg/bin/pdc.phar && php pdc.phar src"